// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Pawn.h"
#include "Templates/SubclassOf.h"
#include "RocketSectionMotion.h"
#include "RocketPawn.generated.h"

class UJSBSimMovementComponent;
class URocketFlightController;
class URocketTelemetryWidget;
class URocketUdpBridge;
class UStaticMeshComponent;
class UInstancedStaticMeshComponent;
class UProceduralMeshComponent;
class UCableComponent;
class UCameraComponent;
class UNiagaraComponent;
class UNiagaraSystem;
class UMaterialInstanceDynamic;

/**
 * A ready-to-fly amateur suborbital rocket pawn.
 *
 * Assembles the three pieces needed to launch, fly and recover a rocket on the Cesium globe:
 *   - a procedurally generated airframe (ogive nose, airfoil fins, gored parachutes, simulated
 *     shock cord) that needs no imported assets, plus a swappable single-mesh override,
 *   - a UJSBSimMovementComponent pre-configured for the "rocket" JSBSim model (no trim, motor
 *     off, starts on the pad), which does the ECEF <-> Unreal transform, and
 *   - a URocketFlightController that runs the launch/apogee/recovery state machine.
 *
 * It also provides a world-stabilized chase camera so the flight is watchable when possessed,
 * and (in Manual mode) input bindings to ignite and deploy chutes.
 *
 * Place one in the level, rotate it Pitch = +90 so the nose points at the sky, put it over
 * ground that has collision, then press Play.
 *
 * VISUALS ARE COSMETIC. JSBSim still models the whole tethered recovery train as one rigid
 * body; the section motion, cables and canopies here describe how the pieces hang relative to
 * that body. Changing them cannot affect the trajectory.
 */
UCLASS()
class UNREALSPACEPROGRAM_API ARocketPawn : public APawn
{
	GENERATED_BODY()

public:
	ARocketPawn();

	/**
	 * Optional single-mesh override for the whole rocket (e.g. an imported rocket.glb or your
	 * own model, nose along +X spanning 0..277 cm). When a mesh is assigned here, the
	 * generated section visuals below are hidden and no separation animation plays.
	 */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket")
	TObjectPtr<UStaticMeshComponent> RocketMesh;

	// --- Airframe sections ---
	// The rocket is visualized as three sections that separate during recovery:
	//   booster (with fins)  actor X [0..110] cm  - tail/motor section
	//   upper airframe       actor X [110..215]   - payload/recovery bay
	//   nose cone            actor X [215..277]
	// Each section has a Root scene component at its aft joint (attach custom meshes there and
	// hide the generated mesh to substitute your own), plus a UProceduralMeshComponent whose
	// geometry is regenerated by BuildAirframeGeometry() from the dimensions below.

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Sections")
	TObjectPtr<USceneComponent> BoosterRoot;

	/** Booster body: tube + boat tail + fins + launch lug, welded into one mesh. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Sections")
	TObjectPtr<UProceduralMeshComponent> BoosterMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Sections")
	TObjectPtr<USceneComponent> UpperRoot;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Sections")
	TObjectPtr<UProceduralMeshComponent> UpperMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Sections")
	TObjectPtr<USceneComponent> NoseRoot;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Sections")
	TObjectPtr<UProceduralMeshComponent> NoseMesh;

	// --- Airframe dimensions (drive the generated geometry; regenerate by re-running the
	//     construction script, i.e. moving the actor or pressing Play) ---

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "1.0"))
	float BodyRadiusCm = 7.6f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "1.0"))
	float BoosterLengthCm = 110.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "1.0"))
	float UpperLengthCm = 105.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "1.0"))
	float NoseLengthCm = 62.0f;

	/** Radius at the very tail. Less than BodyRadiusCm gives a boat tail. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "0.5"))
	float BoatTailRadiusCm = 5.6f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "0.0"))
	float BoatTailLengthCm = 9.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "3"))
	int32 FinCount = 4;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "1.0"))
	float FinRootChordCm = 45.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "0.0"))
	float FinTipChordCm = 22.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "1.0"))
	float FinSpanCm = 17.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "0.0"))
	float FinSweepCm = 18.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Airframe", meta = (ClampMin = "0.1"))
	float FinThicknessCm = 1.2f;

	// --- Section colours (applied as dynamic material instances over the engine basic material) ---

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Appearance")
	FLinearColor BoosterColor = FLinearColor(0.05f, 0.05f, 0.06f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Appearance")
	FLinearColor UpperColor = FLinearColor(0.85f, 0.85f, 0.88f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Appearance")
	FLinearColor NoseColor = FLinearColor(0.75f, 0.08f, 0.06f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Appearance")
	FLinearColor DrogueColor = FLinearColor(0.95f, 0.45f, 0.02f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Appearance")
	FLinearColor MainColor = FLinearColor(0.9f, 0.15f, 0.1f);

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Appearance")
	FLinearColor CableColor = FLinearColor(0.25f, 0.22f, 0.2f);

	// --- Parachutes ---
	// Each canopy hangs from a Root that sits at the harness (confluence) point on the airframe
	// and SWINGS as a pendulum. The dome sits LineLength up +X from it, with generated shroud
	// lines running between the two.

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<USceneComponent> DrogueCanopyRoot;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<UProceduralMeshComponent> DrogueCanopyMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<UProceduralMeshComponent> DrogueShroudMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<USceneComponent> MainCanopyRoot;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<UProceduralMeshComponent> MainCanopyMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<UProceduralMeshComponent> MainShroudMesh;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "5.0"))
	float DrogueCanopyRadiusCm = 45.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "10.0"))
	float DrogueLineLengthCm = 90.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "3"))
	int32 DrogueGoreCount = 6;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "5.0"))
	float MainCanopyRadiusCm = 120.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "10.0"))
	float MainLineLengthCm = 180.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "3"))
	int32 MainGoreCount = 8;

	/** Seconds a canopy takes to go from packed to fully inflated. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.05"))
	float CanopyInflateSeconds = 0.8f;

	/** How far the canopy overshoots full size on the opening shock, as a fraction (0.25 = 125%). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.0"))
	float CanopyOpeningOvershoot = 0.25f;

	/** Peak pendulum swing angle (deg) of a canopy under load. Decays as the descent stabilizes. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.0"))
	float CanopySwingAngleDeg = 9.0f;

	/** Pendulum period (seconds) for the canopy swing. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.2"))
	float CanopySwingPeriodSeconds = 3.2f;

	// --- Canopy response to the airflow ---
	// The canopy is oriented against the AIR-RELATIVE velocity that JSBSim computes, so wind
	// and turbulence set into the FDM show up here automatically: the chute leans downwind,
	// shudders in gusts and breathes, all without a separate wind model.

	/** How quickly the canopy swings to face the airflow (per second). Low = lazy, laggy chute. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.1"))
	float CanopyLeanResponse = 2.5f;

	/** Peak extra tilt (deg) the canopy flutters by in the airflow, at FlutterReferenceSpeed. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.0"))
	float CanopyFlutterDeg = 6.0f;

	/** Airspeed (ft/s) at which flutter and breathing reach full strength. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "1.0"))
	float FlutterReferenceSpeedFps = 70.0f;

	/** How much the canopy "breathes" (radius pulsing) under load, as a fraction of radius. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.0", ClampMax = "0.5"))
	float CanopyBreathAmount = 0.05f;

	/** Extra cable length beyond the straight-line endpoint distance, as a fraction. Gives the
	 *  shock cord a natural catenary instead of a taut string or a wild loop. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.0"))
	float CableSlackFactor = 0.12f;

	// --- Tethers (simulated cables, so they sag and swing under load) ---

	/** Shock cord from the booster up to the payload bay. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<UCableComponent> ShockCord;

	/** Short tether keeping the ejected nose cone attached to the payload bay. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery")
	TObjectPtr<UCableComponent> NoseTether;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "10.0"))
	float ShockCordLengthCm = 170.0f;

	/** Tether from the ejected nose section down to the payload bay. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "10.0"))
	float NoseTetherLengthCm = 130.0f;

	/** How far the payload bay may wander from the main's bridle point once the main is out. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "1.0"))
	float MainBridleLengthCm = 40.0f;

	/**
	 * Pendulum swing acceleration (cm/s^2) applied across the airflow to hanging sections.
	 *
	 * Distinct from SectionBuffetScale: buffeting is random and reads as shudder, this is a
	 * coherent oscillation at CanopySwingPeriodSeconds and is what actually makes the train
	 * look like it is swinging beneath a canopy.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Recovery", meta = (ClampMin = "0.0"))
	float SectionSwingAccel = 260.0f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Rocket|Recovery", meta = (ClampMin = "0.1"))
	float CableWidthCm = 0.7f;

	// --- Separation dynamics ---

	/** Speed (cm/s) the booster is kicked away from the payload bay at separation. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0"))
	float BoosterEjectSpeed = 220.0f;

	/** Speed (cm/s) the nose cone is thrown off by the ejection charge. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0"))
	float NoseEjectSpeed = 340.0f;

	/** Tumble imparted at separation, degrees/sec, randomized per axis. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0"))
	float SeparationTumbleRate = 150.0f;

	/** Random spread (deg) applied to the ejection direction so runs are not identical. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0"))
	float SeparationConeAngleDeg = 18.0f;

	/** Acceleration (cm/s^2) settling a loose section down its cord once the chute is holding. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation")
	float SectionSettleAccel = 420.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float SectionLinearDamping = 0.55f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float SectionAngularDamping = 0.9f;

	/** How strongly a settled section swings round to hang along its cord (per second). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0"))
	float SectionAlignStrength = 1.6f;

	/** Buffeting acceleration (cm/s^2) per 100 ft/s of airspeed, shaking sections in the airflow. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Separation", meta = (ClampMin = "0.0"))
	float SectionBuffetScale = 140.0f;

	// --- Effects ---
	// Every Niagara slot is OPTIONAL. Leave one unset and the code-built fallback below is used
	// instead, so the rocket has visible exhaust and smoke with no authored assets at all.
	// Assign a system to a slot and the fallback for that effect is disabled automatically.

	/** Continuous motor exhaust. Activated at ignition, deactivated at burnout. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects")
	TObjectPtr<UNiagaraSystem> ExhaustEffect;

	/** One-shot burst at ignition (pad smoke / flame wash). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects")
	TObjectPtr<UNiagaraSystem> IgnitionEffect;

	/** One-shot burst when the airframe separates (ejection charge). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects")
	TObjectPtr<UNiagaraSystem> SeparationEffect;

	/** One-shot burst at touchdown (dust). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects")
	TObjectPtr<UNiagaraSystem> LandingEffect;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Effects")
	TObjectPtr<UNiagaraComponent> ExhaustFX;

	/** Code-built exhaust plume, used when ExhaustEffect is unset. Scales with live thrust. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Effects")
	TObjectPtr<UProceduralMeshComponent> ExhaustPlumeMesh;

	/** Code-built smoke trail, used when ExhaustEffect is unset. A ring buffer of puffs. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket|Effects")
	TObjectPtr<UInstancedStaticMeshComponent> SmokePuffs;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects", meta = (ClampMin = "0.0"))
	float PlumeLengthCm = 130.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects")
	FLinearColor PlumeColor = FLinearColor(1.0f, 0.55f, 0.15f);

	/** Thrust (lbf) at which the plume reaches full length. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects", meta = (ClampMin = "1.0"))
	float PlumeReferenceThrustLbf = 120.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects", meta = (ClampMin = "0"))
	int32 MaxSmokePuffs = 64;

	/** Seconds between smoke puffs while the motor burns. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects", meta = (ClampMin = "0.005"))
	float SmokePuffInterval = 0.035f;

	/** Seconds a smoke puff lives before it is recycled. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Effects", meta = (ClampMin = "0.1"))
	float SmokePuffLifetime = 3.5f;

	/** The JSBSim flight dynamics bridge (model = "rocket"). */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket")
	TObjectPtr<UJSBSimMovementComponent> JSBSim;

	/** The launch / apogee / recovery state machine and command surface. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket")
	TObjectPtr<URocketFlightController> FlightController;

	/** Chase camera used when this pawn is possessed. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket")
	TObjectPtr<UCameraComponent> ChaseCamera;

	/** UDP hardware-in-the-loop bridge (disabled by default - enable bAutoStart to use). */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Rocket")
	TObjectPtr<URocketUdpBridge> UdpBridge;

	// --- Telemetry widget ---

	/** Show the on-screen telemetry widget when this pawn is possessed by a player. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Telemetry")
	bool bShowTelemetryWidget = true;

	/** Widget class to spawn. Leave unset to use the default code-built URocketTelemetryWidget;
	 *  set a Blueprint subclass here to use your own designer layout. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Telemetry")
	TSubclassOf<URocketTelemetryWidget> TelemetryWidgetClass;

	/** The live telemetry widget instance (created on possession). */
	UPROPERTY(Transient, BlueprintReadOnly, Category = "Rocket|Telemetry")
	TObjectPtr<URocketTelemetryWidget> TelemetryWidget;

	// --- Chase camera framing (world-stabilized so it never tumbles with the rocket) ---
	// In-game controls: mouse wheel zooms; hold the right mouse button and drag to orbit
	// (horizontal = azimuth, vertical = height). Q/E also orbit, Z/C also zoom.

	/** Horizontal distance of the camera from the rocket, in meters. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera", meta = (ClampMin = "1.0"))
	float CameraDistanceMeters = 18.0f;

	/** Height of the camera above the rocket, in meters. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera")
	float CameraHeightMeters = 5.0f;

	/** Compass direction (deg) the camera sits from the rocket (0 = to the north of it). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera")
	float CameraAzimuthDeg = 135.0f;

	/** If true, the chase camera position/aim is updated every frame to track the rocket. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera")
	bool bUseChaseCamera = true;

	/** Zoom factor per mouse-wheel notch (distance is multiplied/divided by this). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera", meta = (ClampMin = "1.01"))
	float CameraZoomStep = 1.15f;

	/** Orbit speed, degrees per pixel of right-button mouse drag. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera", meta = (ClampMin = "0.01"))
	float CameraOrbitSpeed = 0.5f;

	/** Closest / farthest the camera can zoom, in meters. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rocket|Camera")
	FVector2D CameraDistanceRangeMeters = FVector2D(3.0f, 300.0f);

	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;
	virtual void OnConstruction(const FTransform& Transform) override;
	virtual void SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent) override;
	virtual void PossessedBy(AController* NewController) override;
	virtual void UnPossessed() override;

	/** Total rocket length, derived from the section lengths. */
	UFUNCTION(BlueprintPure, Category = "Rocket|Airframe")
	float GetTotalLengthCm() const { return BoosterLengthCm + UpperLengthCm + NoseLengthCm; }

protected:
	// Input handlers (Manual-mode overrides; work any time for testing).
	void HandleIgnite();
	void HandleDeployDrogue();
	void HandleDeployMain();
	void HandleResetFlight();

	// Camera control handlers.
	void HandleZoomWheel(float AxisValue);
	void HandleZoomIn();
	void HandleZoomOut();
	void HandleOrbitStart();
	void HandleOrbitStop();
	void HandleOrbitMouseX(float AxisValue);
	void HandleOrbitMouseY(float AxisValue);
	void HandleOrbitLeft();
	void HandleOrbitRight();

	bool bOrbiting = false;

	void ApplyZoom(float Factor);
	void UpdateChaseCamera();

	// --- Visual construction ---

	/** Regenerate all procedural geometry from the dimension properties. Safe to call repeatedly. */
	void BuildAirframeGeometry();

	/** Create (or refresh) the dynamic material instances used to tint the generated meshes. */
	void ApplySectionMaterials();

	/** Rebuild a canopy's dome + shroud lines at the given inflation fraction (0..1+). */
	void BuildCanopyGeometry(
		UProceduralMeshComponent* CanopyMesh,
		UProceduralMeshComponent* ShroudMesh,
		float Radius,
		float LineLength,
		int32 GoreCount,
		float Inflation);

	// --- Per-frame visual updates ---

	/**
	 * Read the air-relative velocity from JSBSim into AirflowLocal / AirspeedFps.
	 *
	 * JSBSim's velocities/{u,v,w}-aero-fps are the body-frame velocity of the airframe THROUGH
	 * THE AIR, so they already include wind, gusts and turbulence from the FDM's atmosphere.
	 * The plugin builds the actor rotation straight from JSBSim's Euler angles, which makes the
	 * actor frame the body frame with Z flipped (body Z is down, Unreal Z is up) - so the
	 * mapping to actor-local space is just (u, v, -w), with no georeferencing math needed.
	 */
	void SampleAirflow();

	/** Random buffeting acceleration across the airflow, scaled by dynamic pressure. */
	FVector MakeBuffet(float Scale) const;

	/** Coherent pendulum acceleration across the airflow. PhaseOffset staggers each section so
	 *  the train swings as a chain rather than moving as one rigid block. */
	FVector MakeSwing(float Scale, float PhaseOffset) const;

	void UpdateSeparation(float DeltaSeconds);
	void UpdateCanopies(float DeltaSeconds);
	void UpdateCables();
	void UpdateExhaust(float DeltaSeconds);
	void UpdateSmoke(float DeltaSeconds);

	/** Reset all visual state back to the stowed configuration (mirrors ResetFlight). */
	void ResetVisuals();

	/** True when a user mesh in RocketMesh has taken over from the generated sections. */
	bool IsSingleMeshMode() const;

	// --- Runtime visual state ---

	// The recovery train is a hanging CHAIN, matching the FDM's bridle points: the drogue is
	// tied to the aft end of the ejected nose section, the payload bay dangles below the nose
	// on its tether, and the tail hangs below the payload on the shock cord. Each section is
	// anchored to the one above it, so motion propagates down the stack.

	UPROPERTY(Transient)
	FRocketSectionMotion NoseMotion;

	UPROPERTY(Transient)
	FRocketSectionMotion UpperMotion;

	UPROPERTY(Transient)
	FRocketSectionMotion BoosterMotion;

	/** Inflation fraction per canopy, 0 = packed, 1 = fully open (may exceed 1 on opening shock). */
	float DrogueInflation = 0.0f;
	float MainInflation = 0.0f;

	/** Last inflation the canopy geometry was rebuilt at, so we only regenerate when it moves. */
	float DrogueBuiltInflation = -1.0f;
	float MainBuiltInflation = -1.0f;

	/** Seconds since each canopy was deployed, for the opening-shock and swing curves. */
	float DrogueDeployTime = -1.0f;
	float MainDeployTime = -1.0f;

	/** Ring-buffer cursor and timer for the code-built smoke trail. */
	int32 NextSmokePuff = 0;
	float SmokePuffTimer = 0.0f;

	/** Per-puff spawn time (world seconds), parallel to the instance array. -1 = unused. */
	TArray<float> SmokePuffSpawnTimes;
	TArray<FVector> SmokePuffWorldLocations;

	/**
	 * Air-relative velocity in actor-local space, normalized. Points the way the airframe is
	 * moving through the air, so -AirflowLocal is where a canopy sits and +AirflowLocal is
	 * where tethered sections trail. Falls back to -X (body aft) when airspeed is negligible.
	 */
	FVector AirflowLocal = -FVector::XAxisVector;

	/** Magnitude of the air-relative velocity, ft/s. */
	float AirspeedFps = 0.0f;

	/** Ensures the airflow-availability message is logged once per run, not once per frame. */
	bool bLoggedAirflowStatus = false;

	/** Smoothed canopy axis (actor-local), so the chute leans rather than snapping. */
	FVector DrogueAxis = FVector::XAxisVector;
	FVector MainAxis = FVector::XAxisVector;

	/** Tracks separation edges so impulses fire exactly once per event. */
	bool bWasSeparated = false;
	bool bWasMainDeployed = false;
	bool bWasLanded = false;

	UPROPERTY(Transient)
	TObjectPtr<UMaterialInstanceDynamic> PlumeMaterial;

	UPROPERTY(Transient)
	TObjectPtr<UMaterialInstanceDynamic> SmokeMaterial;
};
